<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.5</version>
        <relativePath/>
    </parent>

    <groupId>com.telecom.ossbss</groupId>
    <artifactId>telecom-ossbss</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>

    <name>Telecom OSS BSS</name>
    <description>Telecom OSS/BSS Microservices Platform</description>

    <properties>
        <java.version>17</java.version>
    </properties>

    <modules>
        <module>src/billing-service</module>
        <module>src/cdr-service</module>
        <module>src/customer-service</module>
    </modules>

</project>

